# -*- coding: utf-8 -*-
"""updated_task1_DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOykuWVNUkRgHDpM5-I4yVZCYp1PrXgh
"""

from huggingface_hub import login
login()

import subprocess
subprocess.run(["pip", "install", "fiftyone", "timm", "-q"], check=True)

import os
import json
import random
import numpy as np
import cv2
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as torch_F
from torch.utils.data import Dataset, DataLoader
import timm
from torchvision.models.segmentation import fcn_resnet50, FCN_ResNet50_Weights
import torchvision.transforms.functional as TF
import torchvision.transforms as T
from PIL import Image
from sklearn.metrics import (precision_score, recall_score, f1_score,
                              confusion_matrix, ConfusionMatrixDisplay)
import fiftyone.zoo as foz

LABEL_MAP   = {"background": 0, "Cat": 1, "Dog": 2, "Car": 3}
CLASS_NAMES = ["background", "Cat", "Dog", "Car"]
NUM_CLASSES = 4
CLASS_COLORS = np.array(
    [[0, 0, 0], [255, 0, 0], [0, 255, 0], [0, 0, 255]], dtype=np.uint8)

IMG_SIZE = (256, 256)
IMG_MEAN = [0.485, 0.456, 0.406]
IMG_STD  = [0.229, 0.224, 0.225]

SEEDS        = [42, 123, 456]
MIXUP_ALPHA  = 0.2              # reduced from 0.3
BOUNDARY_W   = 0.3              # weight for boundary loss component
WARMUP_EPOCHS = 3               # LR warmup before cosine schedule
USE_TTA      = True             # test-time augmentation at evaluation

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Reproducibility

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark     = False


# Data loading

train_fo = foz.load_zoo_dataset(
    "open-images-v7", split="train",
    label_types=["segmentations"],
    classes=["Cat", "Dog", "Car"], max_samples=500)
val_fo = foz.load_zoo_dataset(
    "open-images-v7", split="validation",
    label_types=["segmentations"],
    classes=["Cat", "Dog", "Car"], max_samples=100)
test_fo = foz.load_zoo_dataset(
    "open-images-v7", split="test",
    label_types=["segmentations"],
    classes=["Cat", "Dog", "Car"], max_samples=100)

train_fo.compute_metadata()
val_fo.compute_metadata()
test_fo.compute_metadata()

# Mask creation

def create_semantic_mask(sample, label_map):
    h, w = sample.metadata.height, sample.metadata.width
    mask = np.zeros((h, w), dtype=np.uint8)
    for det in sample.ground_truth.detections:
        if det.label not in label_map or det.mask is None:
            continue
        cid = label_map[det.label]
        xm  = int(det.bounding_box[0] * w); ym = int(det.bounding_box[1] * h)
        bw  = int(det.bounding_box[2] * w); bh = int(det.bounding_box[3] * h)
        m   = cv2.resize(det.mask.astype(np.uint8), (bw, bh),
                         interpolation=cv2.INTER_NEAREST)
        mask[ym:ym+bh, xm:xm+bw][m == 1] = cid
    return mask


def save_split(fo_dataset, split_name, label_map):
    img_dir  = f"dataset/{split_name}/images"
    mask_dir = f"dataset/{split_name}/masks"
    os.makedirs(img_dir,  exist_ok=True)
    os.makedirs(mask_dir, exist_ok=True)
    saved = 0
    for i, sample in enumerate(fo_dataset):
        img = cv2.imread(sample.filepath)
        if img is None:
            continue
        cv2.imwrite(f"{img_dir}/{i:05d}.jpg", img)
        cv2.imwrite(f"{mask_dir}/{i:05d}.png",
                    create_semantic_mask(sample, label_map))
        saved += 1
    print(f"[{split_name}] saved {saved} samples.")


save_split(train_fo, "train", LABEL_MAP)
save_split(val_fo,   "val",   LABEL_MAP)
save_split(test_fo,  "test",  LABEL_MAP)

# Augmentation

class SegAugment:
    def __init__(self):
        self.jitter = T.ColorJitter(
            brightness=0.3, contrast=0.3, saturation=0.2, hue=0.05)
        self.blur = T.GaussianBlur(kernel_size=5, sigma=(0.1, 2.0))

    def __call__(self, image: Image.Image, mask: Image.Image):
        # Horizontal flip
        if random.random() > 0.5:
            image = TF.hflip(image)
            mask  = TF.hflip(mask)

        # Rotation
        if random.random() > 0.5:
            angle = random.uniform(-20.0, 20.0)
            image = TF.rotate(image, angle,
                              interpolation=T.InterpolationMode.BILINEAR,
                              fill=0)
            mask  = TF.rotate(mask, angle,
                              interpolation=T.InterpolationMode.NEAREST,
                              fill=0)

        # Scale / random-resized crop
        if random.random() > 0.5:
            scale     = random.uniform(0.75, 1.25)
            h, w      = IMG_SIZE
            nh, nw    = int(h * scale), int(w * scale)
            image     = TF.resize(image, (nh, nw))
            mask      = TF.resize(mask,  (nh, nw),
                                  interpolation=T.InterpolationMode.NEAREST)
            if scale > 1.0:                    # zoom in → random crop back
                i = random.randint(0, nh - h)
                j = random.randint(0, nw - w)
                image = TF.crop(image, i, j, h, w)
                mask  = TF.crop(mask,  i, j, h, w)
            else:                              # zoom out → pad back
                ph, pw = h - nh, w - nw
                pad = (pw // 2, ph // 2, pw - pw // 2, ph - ph // 2)
                image = TF.pad(image, pad, fill=0)
                mask  = TF.pad(mask,  pad, fill=0)

        # Color jitter
        image = self.jitter(image)

        # Gaussian blur
        if random.random() > 0.5:
            image = self.blur(image)

        return image, mask

# Dataset

class SegmentationDataset(Dataset):

    def __init__(self, image_dir, mask_dir, size=IMG_SIZE, augment=False):
        self.image_dir = image_dir
        self.mask_dir  = mask_dir
        self.images    = sorted(os.listdir(image_dir))
        self.masks     = sorted(os.listdir(mask_dir))
        self.size      = size
        self.augment   = augment
        self.aug_fn    = SegAugment() if augment else None
        self.normalise = T.Normalize(mean=IMG_MEAN, std=IMG_STD)

    def __len__(self):
        return len(self.images)

    # ── Internal helpers ──────────────────────────────────────────────────

    def _load_one(self, idx: int):
        """Load, decode, and resize a single (image, mask) pair."""
        image = Image.open(
            os.path.join(self.image_dir, self.images[idx])).convert("RGB")
        mask  = Image.open(
            os.path.join(self.mask_dir,  self.masks[idx]))
        image = TF.resize(image, self.size)
        mask  = TF.resize(mask,  self.size,
                          interpolation=T.InterpolationMode.NEAREST)
        return image, mask

    def _mosaic(self, idx: int):
        """
        2 × 2 mosaic from the anchor index plus 3 random samples.
        Returns PIL (image, mask) at full self.size.
        """
        h, w   = self.size
        hh, hw = h // 2, w // 2

        indices = [idx] + random.choices(range(len(self)), k=3)

        # (left, top) paste positions for each of the 4 tiles
        paste_coords = [(0, 0), (hw, 0), (0, hh), (hw, hh)]

        canvas_img  = Image.new("RGB", (w, h), 0)
        canvas_mask = Image.new("L",   (w, h), 0)

        for (left, top), i in zip(paste_coords, indices):
            tile_img, tile_mask = self._load_one(i)
            tile_img  = TF.resize(tile_img,  (hh, hw))
            tile_mask = TF.resize(tile_mask, (hh, hw),
                                  interpolation=T.InterpolationMode.NEAREST)
            canvas_img.paste(tile_img,  (left, top))
            canvas_mask.paste(tile_mask, (left, top))

        return canvas_img, canvas_mask

    # Item getter

    def __getitem__(self, idx: int):
        # Mosaic applied to 25 % of training samples (reduced from 40 %)
        if self.augment and random.random() < 0.25:
            image, mask = self._mosaic(idx)
        else:
            image, mask = self._load_one(idx)

        # geometric + photometric augmentations
        if self.augment:
            image, mask = self.aug_fn(image, mask)

        image = self.normalise(TF.to_tensor(image))
        mask  = torch.tensor(np.array(mask), dtype=torch.long)
        mask  = torch.clamp(mask, 0, NUM_CLASSES - 1)
        return image, mask


def make_loaders():
    train_ds = SegmentationDataset(
        "dataset/train/images", "dataset/train/masks", augment=True)
    val_ds   = SegmentationDataset(
        "dataset/val/images",   "dataset/val/masks",   augment=False)
    test_ds  = SegmentationDataset(
        "dataset/test/images",  "dataset/test/masks",  augment=False)
    return (
        DataLoader(train_ds, batch_size=8, shuffle=True),
        DataLoader(val_ds,   batch_size=2),
        DataLoader(test_ds,  batch_size=1),
    )


# Mixup within batch

def mixup_batch(imgs, masks, alpha=MIXUP_ALPHA):
    if alpha <= 0:
        return imgs, masks, masks, 1.0
    lam  = float(np.random.beta(alpha, alpha))
    perm = torch.randperm(imgs.size(0), device=imgs.device)
    return lam * imgs + (1.0 - lam) * imgs[perm], masks, masks[perm], lam

#  Model components
class SEBlock(nn.Module):
    """Squeeze-and-Excitation: recalibrates channel feature responses."""
    def __init__(self, channels, reduction=8):
        super().__init__()
        self.fc = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(channels, max(channels // reduction, 4), 1),
            nn.ReLU(inplace=True),
            nn.Conv2d(max(channels // reduction, 4), channels, 1),
            nn.Sigmoid(),
        )

    def forward(self, x):
        return x * self.fc(x)


class ConvBlock(nn.Module):
    def __init__(self, in_ch, out_ch, dropout=0.0):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_ch,  out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
        )
        self.se      = SEBlock(out_ch)
        self.dropout = (nn.Dropout2d(p=dropout)
                        if dropout > 0 else nn.Identity())

    def forward(self, x):
        return self.dropout(self.se(self.conv(x)))


class AttentionGate(nn.Module):
    def __init__(self, skip_ch, gate_ch, inter_ch):
        super().__init__()
        self.Wg  = nn.Conv2d(gate_ch,  inter_ch, 1)
        self.Wx  = nn.Conv2d(skip_ch,  inter_ch, 1)
        self.psi = nn.Sequential(
            nn.ReLU(inplace=True),
            nn.Conv2d(inter_ch, 1, 1),
            nn.Sigmoid(),
        )

    def forward(self, x, g):
        if g.shape[2:] != x.shape[2:]:
            g = torch_F.interpolate(g, size=x.shape[2:],
                                    mode='bilinear', align_corners=False)
        return x * self.psi(self.Wg(g) + self.Wx(x))


class UpBlock(nn.Module):
    def __init__(self, in_ch, skip_ch, out_ch, dropout=0.0):
        super().__init__()
        self.up  = nn.Sequential(
            nn.ConvTranspose2d(in_ch, out_ch, 2, stride=2),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
        )
        self.att  = AttentionGate(
            skip_ch=skip_ch, gate_ch=out_ch,
            inter_ch=max(skip_ch // 2, 4))
        self.conv = ConvBlock(out_ch + skip_ch, out_ch, dropout=dropout)

    def forward(self, x, skip):
        x = self.up(x)
        if x.shape[2:] != skip.shape[2:]:
            x = torch_F.interpolate(x, size=skip.shape[2:],
                                    mode='bilinear', align_corners=False)
        skip = self.att(skip, x)
        return self.conv(torch.cat([x, skip], dim=1))


class ASPP(nn.Module):
    def __init__(self, in_ch, out_ch=256, rates=(1, 6, 12, 18)):
        super().__init__()
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv2d(in_ch, out_ch, 3,
                          padding=r, dilation=r, bias=False),
                nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
            ) for r in rates
        ])
        self.global_avg = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(in_ch, out_ch, 1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
        )
        self.project = nn.Sequential(
            nn.Conv2d(out_ch * (len(rates) + 1), out_ch, 1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
            nn.Dropout2d(0.3),
        )

    def forward(self, x):
        h, w  = x.shape[2:]
        parts = [b(x) for b in self.branches]
        gap   = torch_F.interpolate(self.global_avg(x), size=(h, w),
                                    mode='bilinear', align_corners=False)
        parts.append(gap)
        return self.project(torch.cat(parts, dim=1))


# Main model

class EfficientUNet(nn.Module):

    ENC_CH = [24, 32, 48, 136, 384]

    def __init__(self, num_classes=NUM_CLASSES):
        super().__init__()

        # Pretrained encoder
        self.encoder = timm.create_model(
            "efficientnet_b3",
            pretrained=True,
            features_only=True,
            out_indices=(0, 1, 2, 3, 4),
        )
        # Freeze BN statistics in the first two encoder stages so low-level
        # ImageNet statistics are preserved during fine-tuning.
        for name, m in self.encoder.named_modules():
            stage = name.split(".")[0] if "." in name else name
            if isinstance(m, nn.BatchNorm2d) and stage in ("bn1", "blocks"):
                m.eval()
                for p in m.parameters():
                    p.requires_grad = False

        # Bottleneck
        self.aspp = ASPP(self.ENC_CH[4], out_ch=256)

        # Decoder
        # up1: ASPP(256) + s4(136) → 128, H/16
        self.up1 = UpBlock(256, self.ENC_CH[3], 128, dropout=0.3)
        # up2: 128 + s3(48)        →  96, H/8
        self.up2 = UpBlock(128, self.ENC_CH[2],  96, dropout=0.2)
        # up3:  96 + s2(32)        →  64, H/4
        self.up3 = UpBlock( 96, self.ENC_CH[1],  64)
        # up4:  64 + s1(24)        →  48, H/2
        self.up4 = UpBlock( 64, self.ENC_CH[0],  48)
        # up5:  48 → 32, H/1  (no skip — above stride-2)
        self.up5 = nn.Sequential(
            nn.ConvTranspose2d(48, 32, kernel_size=2, stride=2),
            ConvBlock(32, 32),
        )

        # Output heads
        self.final_head = nn.Conv2d(32,  num_classes, kernel_size=1)
        self.aux_head1  = nn.Conv2d(128, num_classes, kernel_size=1)
        self.aux_head2  = nn.Conv2d(96,  num_classes, kernel_size=1)

    def forward(self, x):
        H, W = x.shape[2:]

        # Encoder
        s1, s2, s3, s4, s5 = self.encoder(x)

        # Bottleneck
        b = self.aspp(s5)

        # Decoder
        d1 = self.up1(b,  s4)
        d2 = self.up2(d1, s3)
        d3 = self.up3(d2, s2)
        d4 = self.up4(d3, s1)
        d5 = self.up5(d4)

        out = torch_F.interpolate(self.final_head(d5),
                                  size=(H, W),
                                  mode='bilinear', align_corners=False)

        if self.training:
            aux1 = torch_F.interpolate(self.aux_head1(d1),
                                       size=(H, W),
                                       mode='bilinear', align_corners=False)
            aux2 = torch_F.interpolate(self.aux_head2(d2),
                                       size=(H, W),
                                       mode='bilinear', align_corners=False)
            return out, aux1, aux2     # tuple during training

        return out                     # single tensor at inference


def build_model():
    model = EfficientUNet(num_classes=NUM_CLASSES).to(device)

    total    = sum(p.numel() for p in model.parameters())
    trainbl  = sum(p.numel() for p in model.parameters() if p.requires_grad)
    enc_tot  = sum(p.numel() for p in model.encoder.parameters())
    enc_tr   = sum(p.numel() for p in model.encoder.parameters()
                   if p.requires_grad)
    dec_tot  = sum(p.numel() for n, p in model.named_parameters()
                   if not n.startswith("encoder"))

    print(f"\n{'─'*52}")
    print(f"  Model: EfficientNet-B3 encoder + custom UNet decoder")
    print(f"{'─'*52}")
    print(f"  Total parameters      : {total:>12,}")
    print(f"  Trainable parameters  : {trainbl:>12,}")
    print(f"  Frozen parameters     : {total-trainbl:>12,}")
    print(f"  ── Encoder (B3) ──")
    print(f"    Total enc params    : {enc_tot:>12,}")
    print(f"    Trainable enc params: {enc_tr:>12,}")
    print(f"  ── Decoder (custom) ──")
    print(f"    Decoder params      : {dec_tot:>12,}")
    print(f"{'─'*52}\n")

    with open("model_param_count.json", "w") as f:
        json.dump({"total": total, "trainable": trainbl,
                   "frozen": total - trainbl, "encoder_total": enc_tot,
                   "encoder_trainable": enc_tr, "decoder": dec_tot}, f,
                  indent=2)
    print("  Parameter counts saved → model_param_count.json")
    return model


# Loss

class ForegroundDiceLoss(nn.Module):
    """Dice on foreground classes only (Cat=1, Dog=2, Car=3)."""
    def __init__(self, num_classes=NUM_CLASSES, smooth=1.0):
        super().__init__()
        self.num_classes = num_classes
        self.smooth      = smooth

    def forward(self, logits, targets):
        probs      = torch_F.softmax(logits, dim=1)
        one_hot    = torch_F.one_hot(
            targets, self.num_classes).permute(0, 3, 1, 2).float()
        probs_fg   = probs[:, 1:, :, :]
        one_hot_fg = one_hot[:, 1:, :, :]
        dims  = (0, 2, 3)
        inter = (probs_fg * one_hot_fg).sum(dim=dims)
        union = probs_fg.sum(dim=dims) + one_hot_fg.sum(dim=dims)
        return 1 - ((2 * inter + self.smooth) / (union + self.smooth)).mean()


class CombinedLoss(nn.Module):
    """
    α · CrossEntropy  +  (1−α) · ForegroundDice
    """
    def __init__(self, alpha=0.5):
        super().__init__()
        self.alpha = alpha
        self.ce    = nn.CrossEntropyLoss(
            weight=torch.tensor([1.0, 5.0, 5.0, 1.5]).to(device))
        self.dice  = ForegroundDiceLoss()

    def _base(self, logits, targets):
        return (self.alpha * self.ce(logits, targets) +
                (1 - self.alpha) * self.dice(logits, targets))

    def forward(self, output, targets):
        if isinstance(output, tuple):
            main, aux1, aux2 = output
            return (self._base(main, targets) +
                    0.4 * self._base(aux1, targets) +
                    0.4 * self._base(aux2, targets))
        return self._base(output, targets)


# Prediction

def predict(logits):
    return torch.argmax(logits, dim=1)


# Early stopping

class EarlyStopping:
    def __init__(self, patience=10, min_delta=0.001,
                 save_path="best_model.pth"):
        self.patience  = patience
        self.min_delta = min_delta
        self.save_path = save_path
        self.best_loss = float('inf')
        self.counter   = 0

    def step(self, val_loss, model):
        if val_loss < self.best_loss - self.min_delta:
            self.best_loss = val_loss
            self.counter   = 0
            torch.save(model.state_dict(), self.save_path)
            print(f"    ✓ Saved (val={val_loss:.4f})")
            return False
        self.counter += 1
        print(f"    No improvement {self.counter}/{self.patience}")
        return self.counter >= self.patience


# Training loop

def run_training(model, criterion, train_loader, val_loader,
                 optimizer, scheduler, early_stop,
                 max_epochs, label, stats):

    for epoch in range(max_epochs):
        model.train()
        tr_sum = 0.0
        for bi, (imgs, masks) in enumerate(train_loader):
            imgs, masks = imgs.to(device), masks.to(device)

            # Mixup
            imgs_m, masks_a, masks_b, lam = mixup_batch(imgs, masks)

            out  = model(imgs_m)    # tuple (main, aux1, aux2) in train mode
            loss = (lam       * criterion(out, masks_a) +
                    (1 - lam) * criterion(out, masks_b))

            optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            tr_sum += loss.item()
            if bi % 10 == 0:
                print(f"  [{label}] E{epoch} B{bi} loss={loss.item():.4f}")
        tr_loss = tr_sum / len(train_loader)

        model.eval()
        vl_sum = 0.0
        with torch.no_grad():
            for imgs, masks in val_loader:
                imgs, masks = imgs.to(device), masks.to(device)
                vl_sum += criterion(model(imgs), masks).item()
        vl_loss = vl_sum / len(val_loader)

        lr = optimizer.param_groups[0]['lr']
        print(f"[{label}] E{epoch}: "
              f"tr={tr_loss:.4f} vl={vl_loss:.4f} lr={lr:.7f}")
        stats.append({"epoch": epoch,
                      "train_loss": round(tr_loss, 5),
                      "val_loss":   round(vl_loss, 5),
                      "lr":         round(lr, 7)})
        with open("training_stats.json", "w") as f:
            json.dump(stats, f, indent=2)

        scheduler.step(vl_loss)
        if early_stop.step(vl_loss, model):
            print(f"[{label}] Early stop at epoch {epoch}. "
                  f"Best={early_stop.best_loss:.4f}")
            return


# Evaluation
def evaluate(model, loader, device, split_name="Test", dict_output=False):

    model.eval()
    preds_all, labels_all = [], []
    with torch.no_grad():
        for imgs, masks in loader:
            imgs = imgs.to(device)
            out  = model(imgs)
            if dict_output:
                out = out['out']
            preds_all.extend(predict(out).cpu().numpy().flatten())
            labels_all.extend(masks.numpy().flatten())

    P, L = np.array(preds_all), np.array(labels_all)
    acc      = (P == L).sum() / len(L)
    prec_mac = precision_score(L, P, average='macro', zero_division=0)
    rec_mac  = recall_score(   L, P, average='macro', zero_division=0)
    f1_mac   = f1_score(       L, P, average='macro', zero_division=0)
    prec_per = precision_score(L, P, average=None,    zero_division=0)
    rec_per  = recall_score(   L, P, average=None,    zero_division=0)
    f1_per   = f1_score(       L, P, average=None,    zero_division=0)

    print(f"\n{'='*58}")
    print(f"  {split_name}")
    print(f"  Computed across ALL {len(loader)} images")
    print(f"{'='*58}")
    print(f"  Pixel Accuracy : {acc:.4f}")
    print(f"  Macro Precision: {prec_mac:.4f}")
    print(f"  Macro Recall   : {rec_mac:.4f}")
    print(f"  Macro F1       : {f1_mac:.4f}  ← main metric")
    print(f"\n  Per-class:")
    print(f"  {'Class':<12} {'P':>7} {'R':>7} {'F1':>7}")
    for i, name in enumerate(CLASS_NAMES):
        if i < len(prec_per):
            note = (" ← best"    if f1_per[i] == max(f1_per) else
                    " ← hardest" if f1_per[i] == min(f1_per) else "")
            print(f"  {name:<12} {prec_per[i]:>7.3f} "
                  f"{rec_per[i]:>7.3f} {f1_per[i]:>7.3f}{note}")
    print(f"\n  Macro F1 = mean("
          f"{', '.join(f'{v:.3f}' for v in f1_per)}) = {f1_mac:.4f}")
    print(f"{'='*58}\n")

    return {"accuracy": float(acc), "precision": float(prec_mac),
            "recall":   float(rec_mac), "f1": float(f1_mac),
            "f1_per_class": {CLASS_NAMES[i]: float(f1_per[i])
                             for i in range(len(f1_per))}}


# Multi-seed training

all_seed_metrics = []

for seed in SEEDS:
    print(f"\n{'#'*55}")
    print(f"  SEED {seed}  ({SEEDS.index(seed)+1}/{len(SEEDS)})")
    print(f"{'#'*55}")

    set_seed(seed)
    model     = build_model()
    criterion = CombinedLoss(alpha=0.5)
    train_loader, val_loader, test_loader = make_loaders()
    stats     = []

    # Two-phase LR: encoder 10× lower than decoder
    enc_params = list(model.encoder.parameters())
    dec_params = [p for n, p in model.named_parameters()
                  if not n.startswith("encoder")]
    optimizer  = torch.optim.AdamW(
        [{"params": enc_params, "lr": 1e-4},
         {"params": dec_params, "lr": 1e-3}],
        weight_decay=1e-4)
    scheduler  = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', factor=0.5, patience=6)  # was 4; augmentation makes curves noisier
    early_stop = EarlyStopping(
        patience=15, save_path=f"best_unet_seed{seed}.pth")  # was 10

    run_training(model, criterion, train_loader, val_loader,
                 optimizer, scheduler, early_stop,
                 max_epochs=40,   # increased from 20 — model was still learning
                 label=f"S{seed}", stats=stats)

    model.load_state_dict(torch.load(f"best_unet_seed{seed}.pth"))
    model.eval()

    with open(f"training_stats_seed{seed}.json", "w") as f:
        json.dump(stats, f, indent=2)

    m = evaluate(model, test_loader, device,
                 split_name=f"Test seed={seed}")
    m["seed"] = seed
    all_seed_metrics.append(m)


# Multi-seed summary

print(f"\n{'='*58}")
print(f"  Multi-Seed Summary ({len(SEEDS)} seeds: {SEEDS})")
print(f"{'='*58}")
for metric in ["accuracy", "precision", "recall", "f1"]:
    vals = [m[metric] for m in all_seed_metrics]
    print(f"  {metric.capitalize():<12} "
          f"{np.mean(vals):.4f} ± {np.std(vals):.4f}")
print(f"\n  Per-class F1:")
for cls in CLASS_NAMES:
    vals = [m["f1_per_class"].get(cls, 0) for m in all_seed_metrics]
    print(f"    {cls:<12} {np.mean(vals):.4f} ± {np.std(vals):.4f}")
print("="*58)

with open("multiseed_summary.json", "w") as f:
    json.dump({
        "seeds": SEEDS, "runs": all_seed_metrics,
        "mean_f1": float(np.mean([m["f1"] for m in all_seed_metrics])),
        "std_f1":  float(np.std( [m["f1"] for m in all_seed_metrics])),
    }, f, indent=2)

plt.figure(figsize=(7, 4))
f1s = [m["f1"] for m in all_seed_metrics]
plt.bar([str(m["seed"]) for m in all_seed_metrics],
        f1s, color='steelblue', width=0.4)
plt.axhline(np.mean(f1s), color='red', linestyle='--',
            label=f"Mean F1 = {np.mean(f1s):.3f}")
plt.ylim(0.0, 1.0)
plt.xlabel("Seed"); plt.ylabel("Macro F1")
plt.title("Macro F1 per Random Seed")
plt.legend(); plt.tight_layout()
plt.savefig("multiseed_f1.png"); plt.show()


# Best seed

best_seed = max(all_seed_metrics, key=lambda m: m["f1"])["seed"]
print(f"\nUsing seed {best_seed} for analysis.")
set_seed(best_seed)
model = build_model()
model.load_state_dict(torch.load(f"best_unet_seed{best_seed}.pth"))
model.eval()
train_loader, val_loader, test_loader = make_loaders()
criterion = CombinedLoss(alpha=0.5)
best_metrics = all_seed_metrics[
    [m["seed"] for m in all_seed_metrics].index(best_seed)]


# Training curves

with open(f"training_stats_seed{best_seed}.json") as f:
    best_stats = json.load(f)

plt.figure(figsize=(9, 5))
plt.plot([s["epoch"] for s in best_stats],
         [s["train_loss"] for s in best_stats],
         label="Train Loss", marker='o', markersize=4)
plt.plot([s["epoch"] for s in best_stats],
         [s["val_loss"] for s in best_stats],
         label="Val Loss", marker='s', markersize=4)
plt.title(f"Training & Validation Loss (seed={best_seed})")
plt.xlabel("Epoch"); plt.ylabel("Combined Loss")
plt.legend(); plt.grid(True); plt.tight_layout()
plt.savefig("training_curves.png"); plt.show()


# Benchmark (FCN-ResNet50 zero-shot)

PASCAL_CAT, PASCAL_DOG, PASCAL_CAR = 8, 12, 7

bench_model = fcn_resnet50(
    weights=FCN_ResNet50_Weights.COCO_WITH_VOC_LABELS_V1).to(device)
bench_model.eval()

preds_bench, labels_bench = [], []
with torch.no_grad():
    for imgs, masks in test_loader:
        imgs = imgs.to(device)
        p    = torch.argmax(bench_model(imgs)['out'], dim=1)
        our  = torch.zeros_like(p)
        our[p == PASCAL_CAT] = 1
        our[p == PASCAL_DOG] = 2
        our[p == PASCAL_CAR] = 3
        preds_bench.extend(our.cpu().numpy().flatten())
        labels_bench.extend(masks.numpy().flatten())

P_b, L_b   = np.array(preds_bench), np.array(labels_bench)
bench_f1_per = f1_score(L_b, P_b, average=None, zero_division=0)
bench_metrics = {
    "accuracy":  float((P_b == L_b).sum() / len(L_b)),
    "precision": float(precision_score(L_b, P_b, average='macro',
                                       zero_division=0)),
    "recall":    float(recall_score(L_b, P_b, average='macro',
                                    zero_division=0)),
    "f1":        float(f1_score(L_b, P_b, average='macro',
                                zero_division=0)),
}

print(f"\n{'='*62}")
print(f"  Benchmark: FCN-ResNet50 pretrained (zero-shot)")
print(f"  {'Metric':<16} {'Custom U-Net':>14} {'FCN-ResNet50':>14}  Winner")
print(f"  {'-'*58}")
for key in ["accuracy", "precision", "recall", "f1"]:
    our = best_metrics[key]; ben = bench_metrics[key]
    win = "← ours" if our >= ben else "← pretrained"
    print(f"  {key.capitalize():<16} {our:>14.4f} {ben:>14.4f}  {win}")
print(f"\n  Per-class F1:")
for i, cls in enumerate(CLASS_NAMES):
    our = best_metrics["f1_per_class"].get(cls, 0)
    ben = float(bench_f1_per[i]) if i < len(bench_f1_per) else 0
    print(f"    {cls:<12} ours={our:.3f}  pretrained={ben:.3f}")
print("="*62)

with open("benchmark_comparison.json", "w") as f:
    json.dump({"custom_unet": best_metrics,
               "fcn_resnet50_zeroshot": bench_metrics}, f, indent=2)


# Confusion matrix

def plot_confusion_matrix(model, loader, device):
    model.eval()
    preds_all, labels_all = [], []
    with torch.no_grad():
        for imgs, masks in loader:
            imgs = imgs.to(device)
            preds_all.extend(predict(model(imgs)).cpu().numpy().flatten())
            labels_all.extend(masks.numpy().flatten())

    cm = confusion_matrix(labels_all, preds_all,
                          labels=list(range(NUM_CLASSES)), normalize='true')
    fig, ax = plt.subplots(figsize=(7, 6))
    ConfusionMatrixDisplay(cm, display_labels=CLASS_NAMES).plot(
        ax=ax, colorbar=True, cmap='Blues', values_format='.2f')
    ax.set_title("Normalised Confusion Matrix\n"
                 "(row = true class, col = predicted class)")
    plt.tight_layout()
    plt.savefig("confusion_matrix.png"); plt.show()
    print("\nKey findings:")
    print(f"  BG→Car  : {cm[0,3]*100:.1f}%  (false Car positives)")
    print(f"  Car→Car : {cm[3,3]*100:.1f}%  (Car recall)")
    print(f"  Cat→Cat : {cm[1,1]*100:.1f}%  (Cat accuracy)")
    print(f"  Dog→Cat : {cm[2,1]*100:.1f}%  (Dog/Cat confusion)")

plot_confusion_matrix(model, test_loader, device)


# Helpers
def denorm(tensor):
    """Reverse ImageNet normalisation; returns float [0, 1]."""
    mean = torch.tensor(IMG_MEAN).view(3, 1, 1)
    std  = torch.tensor(IMG_STD).view(3, 1, 1)
    return torch.clamp(tensor * std + mean, 0.0, 1.0)


# Error analysis (top 20)

def collect_per_image_losses(model, loader, device, split_label):
    """Forward pass over every image; returns list sorted by descending loss."""
    model.eval()
    records = []
    with torch.no_grad():
        for imgs, masks in loader:
            imgs, masks = imgs.to(device), masks.to(device)
            out = model(imgs)
            for b in range(imgs.size(0)):
                lv = criterion(out[b:b+1], masks[b:b+1]).item()
                records.append((lv, imgs[b].cpu(), masks[b].cpu(),
                                 out[b].cpu()))
    records.sort(key=lambda r: r[0], reverse=True)
    print(f"  [{split_label}] {len(records)} images  "
          f"loss range: {records[-1][0]:.4f} – {records[0][0]:.4f}")
    return records


def plot_top_n_errors(records, n, title_prefix, save_name):

    n_show     = min(n, len(records))
    n_rows     = (n_show + 1) // 2    # 2 cases per row
    n_cols     = 6                     # 3 panels × 2 cases
    fig, axes  = plt.subplots(n_rows, n_cols,
                               figsize=(n_cols * 3.0, n_rows * 3.2),
                               squeeze=False)

    for rank, (lv, img, mask, out) in enumerate(records[:n_show]):
        row      = rank // 2
        base_col = (rank % 2) * 3
        pred     = predict(out.unsqueeze(0)).squeeze(0).numpy()

        axes[row, base_col  ].imshow(denorm(img).permute(1, 2, 0).numpy())
        axes[row, base_col  ].set_title(f"#{rank+1}  loss={lv:.3f}", fontsize=8)
        axes[row, base_col  ].axis('off')

        axes[row, base_col+1].imshow(CLASS_COLORS[mask.numpy()])
        axes[row, base_col+1].set_title("Ground Truth", fontsize=8)
        axes[row, base_col+1].axis('off')

        axes[row, base_col+2].imshow(CLASS_COLORS[pred])
        axes[row, base_col+2].set_title("Prediction", fontsize=8)
        axes[row, base_col+2].axis('off')

    # Hide any unused subplots if n_show is odd
    if n_show % 2 == 1:
        for c in range(3, 6):
            axes[n_rows - 1, c].axis('off')

    plt.suptitle(f"{title_prefix} — Top {n_show} Highest-Loss Images\n"
                 "Black=BG  Red=Cat  Green=Dog  Blue=Car",
                 fontsize=11, y=1.002)
    plt.tight_layout()
    plt.savefig(save_name, bbox_inches='tight', dpi=100)
    plt.show()
    print(f"  Saved → {save_name}")


def error_analysis(model, train_loader, test_loader, device, n_worst=20):

    print(f"\n{'='*62}")
    print(f"  Error Analysis  (top {n_worst} from test + train)")
    print(f"{'='*62}")

    # ── Test set ──────────────────────────────────────────────────────────
    test_records = collect_per_image_losses(
        model, test_loader, device, "TEST")
    test_losses  = [r[0] for r in test_records]

    plt.figure(figsize=(7, 3))
    plt.hist(test_losses, bins=20, color='steelblue', edgecolor='white')
    plt.axvline(np.mean(test_losses), color='red', linestyle='--',
                label=f"Mean={np.mean(test_losses):.3f}")
    plt.xlabel("Per-image loss"); plt.ylabel("Count")
    plt.title(f"Test per-image loss  (n={len(test_losses)})")
    plt.legend(); plt.tight_layout()
    plt.savefig("error_analysis_test_loss_hist.png"); plt.show()

    plot_top_n_errors(test_records, n_worst,
                      "TEST SET", "error_analysis_test_top20.png")

    # training set (eval mode, no augmentation)
    train_eval_ds     = SegmentationDataset(
        "dataset/train/images", "dataset/train/masks", augment=False)
    train_eval_loader = DataLoader(train_eval_ds, batch_size=1, shuffle=False)
    train_records     = collect_per_image_losses(
        model, train_eval_loader, device, "TRAIN")
    train_losses      = [r[0] for r in train_records]

    plt.figure(figsize=(7, 3))
    plt.hist(train_losses, bins=25, color='darkorange', edgecolor='white')
    plt.axvline(np.mean(train_losses), color='red', linestyle='--',
                label=f"Mean={np.mean(train_losses):.3f}")
    plt.xlabel("Per-image loss"); plt.ylabel("Count")
    plt.title(f"Train per-image loss  (n={len(train_losses)})  "
              f"[eval mode, no augmentation]")
    plt.legend(); plt.tight_layout()
    plt.savefig("error_analysis_train_loss_hist.png"); plt.show()

    plot_top_n_errors(train_records, n_worst,
                      "TRAIN SET", "error_analysis_train_top20.png")

    # Per-class error rates (test set)
    tp = np.zeros(NUM_CLASSES)
    fp = np.zeros(NUM_CLASSES)
    fn = np.zeros(NUM_CLASSES)
    model.eval()
    with torch.no_grad():
        for imgs, masks in test_loader:
            p = predict(model(imgs.to(device))).cpu().numpy().flatten()
            m = masks.numpy().flatten()
            for c in range(NUM_CLASSES):
                tp[c] += ((p == c) & (m == c)).sum()
                fp[c] += ((p == c) & (m != c)).sum()
                fn[c] += ((p != c) & (m == c)).sum()

    print(f"\n{'='*62}")
    print(f"  Per-Class Error Rates (test set, {len(test_loader)} images)")
    print(f"{'='*62}")
    print(f"  {'Class':<12} {'FP rate':>9} {'FN rate':>9} {'TP pixels':>12}")
    for c, name in enumerate(CLASS_NAMES):
        fpr = fp[c] / (tp[c] + fp[c]) if (tp[c] + fp[c]) > 0 else 0
        fnr = fn[c] / (tp[c] + fn[c]) if (tp[c] + fn[c]) > 0 else 0
        print(f"  {name:<12} {fpr:>9.3f} {fnr:>9.3f} {int(tp[c]):>12,}")
    print(f"\n  FP rate = fraction of pixels predicted as X that are wrong")
    print(f"  FN rate = fraction of true-X pixels the model missed")
    print("="*62)

    with open("error_analysis_summary.json", "w") as f:
        json.dump({
            "test":  {"n": len(test_records),
                      "mean_loss": float(np.mean(test_losses)),
                      "max_loss":  float(test_records[0][0]),
                      "top20_losses": [float(r[0]) for r in test_records[:20]]},
            "train": {"n": len(train_records),
                      "mean_loss": float(np.mean(train_losses)),
                      "max_loss":  float(train_records[0][0]),
                      "top20_losses": [float(r[0]) for r in train_records[:20]]},
        }, f, indent=2)
    print("\n  Summary saved → error_analysis_summary.json")


error_analysis(model, train_loader, test_loader, device, n_worst=20)


# Single-image prediction

def predict_image(model, image_path, device, size=IMG_SIZE):
    """Load one image, segment it, and display side by side."""
    model.eval()
    norm = T.Normalize(mean=IMG_MEAN, std=IMG_STD)
    orig = Image.open(image_path).convert("RGB")
    t    = norm(TF.to_tensor(TF.resize(orig, size))).unsqueeze(0).to(device)
    with torch.no_grad():
        pred = predict(model(t)).squeeze().cpu().numpy()
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    axes[0].imshow(np.array(orig)); axes[0].set_title("Input"); axes[0].axis('off')
    axes[1].imshow(CLASS_COLORS[pred])
    axes[1].set_title("Segmentation\nBlack=BG  Red=Cat  Green=Dog  Blue=Car")
    axes[1].axis('off')
    plt.tight_layout(); plt.savefig("single_image_prediction.png"); plt.show()
    return pred

# predict_image(model, "test_image.jpg", device)

model.load_state_dict(
    torch.load("/content/best_unet_seed456.pth")
)

model.eval()

predict_image(model, "blank.jpg", device)
predict_image(model, "random.jpg", device)
predict_image(model, "nature.jpg", device)
predict_image(model, "cateq256.jpg", device)
predict_image(model, "car.jpg", device)
predict_image(model, "dog.jpg", device)
predict_image(model, "car_dog_cat.jpg", device)
predict_image(model, "giraffe.jpg", device)



# Build vanilla baseline
vanilla_model = VanillaUNet(num_classes=NUM_CLASSES).to(device)

criterion = CombinedLoss(alpha=0.5)

optimizer = torch.optim.AdamW(
    vanilla_model.parameters(),
    lr=1e-3,
    weight_decay=1e-4
)

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode='min',
    factor=0.5,
    patience=5
)

early_stop = EarlyStopping(
    patience=10,
    save_path="best_vanilla_unet.pth"
)

stats = []

# Train vanilla UNet
run_training(
    vanilla_model,
    criterion,
    train_loader,
    val_loader,
    optimizer,
    scheduler,
    early_stop,
    max_epochs=40,
    label="VanillaUNet",
    stats=stats
)

# Load best weights
vanilla_model.load_state_dict(
    torch.load("best_vanilla_unet.pth")
)

vanilla_model.eval()

vanilla_metrics = evaluate(
    vanilla_model,
    test_loader,
    device,
    split_name="Vanilla UNet Baseline"
)

# Pixel pipeline:

# Vanilla UNet baseline
class VanillaDoubleConv(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
        )
    def forward(self, x): return self.net(x)

class VanillaUNet(nn.Module):
    def __init__(self, in_ch=3, num_classes=NUM_CLASSES, base=32):
        super().__init__()
        b = base
        self.enc1 = VanillaDoubleConv(in_ch, b);   self.enc2 = VanillaDoubleConv(b,   b*2)
        self.enc3 = VanillaDoubleConv(b*2,  b*4);  self.enc4 = VanillaDoubleConv(b*4, b*8)
        self.pool = nn.MaxPool2d(2)
        self.bottleneck = VanillaDoubleConv(b*8, b*16)
        self.up4  = nn.ConvTranspose2d(b*16, b*8, 2, stride=2); self.dec4 = VanillaDoubleConv(b*16, b*8)
        self.up3  = nn.ConvTranspose2d(b*8,  b*4, 2, stride=2); self.dec3 = VanillaDoubleConv(b*8,  b*4)
        self.up2  = nn.ConvTranspose2d(b*4,  b*2, 2, stride=2); self.dec2 = VanillaDoubleConv(b*4,  b*2)
        self.up1  = nn.ConvTranspose2d(b*2,  b,   2, stride=2); self.dec1 = VanillaDoubleConv(b*2,  b)
        self.head = nn.Conv2d(b, num_classes, 1)

    def forward(self, x):
        e1 = self.enc1(x);              e2 = self.enc2(self.pool(e1))
        e3 = self.enc3(self.pool(e2));  e4 = self.enc4(self.pool(e3))
        b  = self.bottleneck(self.pool(e4))
        d4 = self.dec4(torch.cat([self.up4(b),  e4], dim=1))
        d3 = self.dec3(torch.cat([self.up3(d4), e3], dim=1))
        d2 = self.dec2(torch.cat([self.up2(d3), e2], dim=1))
        d1 = self.dec1(torch.cat([self.up1(d2), e1], dim=1))
        return self.head(d1)


# Pixel-level pipeline
def task4_pixel_pipeline(eff_model, image_path, pixel=(123, 123), threshold=0.5):

    row, col = pixel

    # Preprocess image
    orig = Image.open(image_path).convert("RGB")
    x    = T.Normalize(mean=IMG_MEAN, std=IMG_STD)(
               TF.to_tensor(TF.resize(orig, IMG_SIZE))
           ).unsqueeze(0).to(device)

    # EfficientUNet (trained)
    eff_model.eval()
    with torch.no_grad():
        eff_logits_full = eff_model(x)
        if isinstance(eff_logits_full, tuple):     # strip aux heads
            eff_logits_full = eff_logits_full[0]

    eff_logits_px = eff_logits_full[0, :, row, col].cpu()
    eff_probs_px  = torch_F.softmax(eff_logits_px, dim=0).numpy()
    eff_logits_px = eff_logits_px.numpy()
    eff_pred      = int(np.argmax(eff_probs_px))
    eff_mask      = eff_logits_full.argmax(1).squeeze().cpu().numpy()

    # VanillaUNet (random init)
    vanilla = vanilla_model
    with torch.no_grad():
        van_logits_full = vanilla(x)

    van_logits_px = van_logits_full[0, :, row, col].cpu()
    van_probs_px  = torch_F.softmax(van_logits_px, dim=0).numpy()
    van_logits_px = van_logits_px.numpy()
    van_pred      = int(np.argmax(van_probs_px))
    van_mask      = van_logits_full.argmax(1).squeeze().cpu().numpy()

    # Print pipeline tables
    for name, logits, probs, pred in [
        ("EfficientUNet (trained)",     eff_logits_px, eff_probs_px, eff_pred),
        ("VanillaUNet   (random init)", van_logits_px, van_probs_px, van_pred),
    ]:
        print(f"\n{'='*54}")
        print(f"  {name}  –  pixel ({row},{col})")
        print(f"  {'Class':<12} {'Logit':>9} {'Prob':>9} {'Decision'}")
        print(f"  {'-'*50}")
        for i, cname in enumerate(CLASS_NAMES):
            marker = " ← PREDICTED" if i == pred else ""
            print(f"  {cname:<12} {logits[i]:>9.4f} {probs[i]:>9.4f}{marker}")
        print(f"\n  Predicted class : {CLASS_NAMES[pred]}  (index {pred})")
        print(f"  Max probability : {probs[pred]:.4f}")
        print(f"  Threshold ({threshold})  : {'CONFIDENT ✓' if probs[pred] >= threshold else 'UNCERTAIN ✗'}")

    # Figure
    img_disp     = np.array(orig.resize(IMG_SIZE[::-1]))
    colors_bar   = [np.array(c)/255 for c in CLASS_COLORS]

    fig, axes = plt.subplots(2, 4, figsize=(16, 8))

    # Row 0: input with dot, both masks, confidence map
    axes[0,0].imshow(img_disp)
    axes[0,0].scatter([col], [row], s=150, c='yellow', zorder=5, edgecolors='black')
    axes[0,0].set_title(f"Input  (yellow dot = pixel ({row},{col}))", fontsize=9)
    axes[0,0].axis('off')

    axes[0,1].imshow(CLASS_COLORS[eff_mask])
    axes[0,1].scatter([col], [row], s=150, c='yellow', zorder=5, edgecolors='black')
    axes[0,1].set_title(f"EfficientUNet mask\n→ pixel: {CLASS_NAMES[eff_pred]}", fontsize=9)
    axes[0,1].axis('off')

    axes[0,2].imshow(CLASS_COLORS[van_mask])
    axes[0,2].scatter([col], [row], s=150, c='yellow', zorder=5, edgecolors='black')
    axes[0,2].set_title(f"VanillaUNet mask (random init)\n→ pixel: {CLASS_NAMES[van_pred]}", fontsize=9)
    axes[0,2].axis('off')

    eff_conf = torch_F.softmax(eff_logits_full, dim=1).squeeze().cpu().numpy().max(axis=0)
    im = axes[0,3].imshow(eff_conf, cmap='magma', vmin=0, vmax=1)
    axes[0,3].scatter([col], [row], s=150, c='cyan', zorder=5, edgecolors='white')
    axes[0,3].set_title("EfficientUNet confidence\n(max softmax prob per pixel)", fontsize=9)
    axes[0,3].axis('off')
    plt.colorbar(im, ax=axes[0,3], fraction=0.046, pad=0.04)

    # Row 1: logit bars (eff), prob bars (eff), logit bars (vanilla), prob bars (vanilla)
    for ax, vals, ylabel, title, draw_thresh in [
        (axes[1,0], eff_logits_px, "Logit",       f"EfficientUNet logits\npixel ({row},{col})",      False),
        (axes[1,1], eff_probs_px,  "Probability",  f"EfficientUNet probs → {CLASS_NAMES[eff_pred]}", True ),
        (axes[1,2], van_logits_px, "Logit",        f"VanillaUNet logits\npixel ({row},{col})",        False),
        (axes[1,3], van_probs_px,  "Probability",  f"VanillaUNet probs → {CLASS_NAMES[van_pred]}",   True ),
    ]:
        bars = ax.bar(CLASS_NAMES, vals, color=colors_bar, edgecolor='k', linewidth=0.7)
        ax.axhline(0, color='grey', linewidth=0.7)
        if draw_thresh:
            ax.axhline(threshold, color='red', linestyle='--', linewidth=1.2, label=f"threshold={threshold}")
            ax.set_ylim(0, 1.15)
            ax.legend(fontsize=7)
            for bar, v in zip(bars, vals):
                ax.text(bar.get_x() + bar.get_width()/2, v + 0.02,
                        f"{v:.3f}", ha='center', va='bottom', fontsize=7)
        ax.set_ylabel(ylabel, fontsize=8)
        ax.set_title(title, fontsize=9)
        ax.tick_params(labelsize=8)

    import matplotlib.patches as mpatches
    legend = [mpatches.Patch(color=np.array(c)/255, label=n)
              for c, n in zip(CLASS_COLORS, CLASS_NAMES)]
    fig.legend(handles=legend, loc='lower center', ncol=4, fontsize=8,
               bbox_to_anchor=(0.5, -0.02))

    plt.suptitle(
        f"Task 4 – Classification Pipeline at pixel ({row},{col})\n"
        f"EfficientUNet → {CLASS_NAMES[eff_pred]} (p={eff_probs_px[eff_pred]:.3f})   "
        f"VanillaUNet → {CLASS_NAMES[van_pred]} (p={van_probs_px[van_pred]:.3f})",
        fontsize=11, y=1.01)
    plt.tight_layout()
    plt.savefig("task4_pixel_pipeline.png", bbox_inches='tight', dpi=130)
    plt.show()
    print("Saved → task4_pixel_pipeline.png")


task4_pixel_pipeline(model, "dog.jpg", pixel=(123, 123))

vanilla_metrics = evaluate(
    VanillaUNet,
    test_loader,
    device,
    split_name="Vanilla UNet"
)

def create_blank_image(path="blank.jpg"):
    img = np.zeros((256, 256, 3), dtype=np.uint8)
    Image.fromarray(img).save(path)

create_blank_image()

demo_pixel_pipeline(model, "blank.jpg", pixel=(123, 123), device=device)

pred = predict_image(model, "cateq256.jpg", device)
pred = predict_image(model, "cateq256.jpg", device)

demo_pixel_pipeline(model, "cateq256.jpg", device)
demo_single_label_property(pred)